#!/usr/bin/env node
/* ════════ The Labs mini-CMS renderer ════════
   Reads {events,library,labs}/data.js and emits one real page per item
   (events/{slug}/index.html …), a directory index per type, and sitemap.xml.
   Idempotent: overwrites in place and removes orphaned generated pages
   (identified by the GENERATED marker — hand-written files are never touched).

   Run:  node tools/generate.js        (then commit data.js + generated pages together)

   Production mapping (docs/OLOS_BACKEND_CHANGES.md §8): these routes are the
   static twins of /events/[slug], /library/[slug], /labs/[slug] — the slug is
   the URL contract; this script plays the part of the server renderer. */
'use strict';
const fs = require('fs'), path = require('path');
const ROOT = path.join(__dirname, '..');
const { EVENTS }    = require(path.join(ROOT, 'events/data.js'));
const { RESOURCES } = require(path.join(ROOT, 'library/data.js'));
const { METROS }    = require(path.join(ROOT, 'labs/data.js'));
const { CYCLE_PUBLIC, SITUATIONS } = require(path.join(ROOT, 'cycles/data.js'));
const { PODS }      = require(path.join(ROOT, 'pods/data.js'));
const { PROJECTS_PUBLIC } = require(path.join(ROOT, 'projects/data.js'));
const { PEOPLE }    = require(path.join(ROOT, 'people/data.js'));
const chrome        = require(path.join(ROOT, 'chrome.js')); // the single nav/footer source (baked here; wired in the browser)
const APPROVED_PROJECTS = PROJECTS_PUBLIC.filter(pr=>pr.approved); // public by artifact: only peer-approved case studies get pages

const MARK = '<!-- GENERATED by tools/generate.js — do not edit. Edit this directory\'s data.js and run `node tools/generate.js`. -->';
/* Public base for canonical/OG URLs + sitemap. Update if the site moves. */
const SITE_BASE = 'https://theupskillinglabs.github.io/onboarding-proto';

const esc = s => String(s||'').replace(/[&<>"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const MO = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
function fmtDate(iso){ const d=new Date(iso); let h=d.getHours(); const ap=h>=12?'PM':'AM'; h=h%12||12; return MO[d.getMonth()]+' '+d.getDate()+' · '+h+' '+ap; }
function fmtDay(iso){ const d=new Date(iso); return ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][d.getDay()]+', '+MO[d.getMonth()]+' '+d.getDate(); }
function fmtTime(iso){ const d=new Date(iso); let h=d.getHours(); const m=d.getMinutes(); const ap=h>=12?'PM':'AM'; h=h%12||12; return h+(m?':'+String(m).padStart(2,'0'):'')+' '+ap; }

/* Same brand orb as shared.js's ORB — self-contained defs, safe to repeat. */
const ORB='<div class="m-orb"><svg viewBox="0 0 240 240" preserveAspectRatio="xMidYMid slice" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" style="display:block;width:100%;height:100%"><defs><radialGradient id="oc" cx="38%" cy="35%" r="58%"><stop offset="0%" stop-color="#0094A0"/><stop offset="62%" stop-color="rgba(0,148,160,0)"/></radialGradient><radialGradient id="or" cx="62%" cy="78%" r="65%"><stop offset="60%" stop-color="rgba(225,29,42,0)"/><stop offset="100%" stop-color="#E11D2A"/></radialGradient><linearGradient id="og" x1="0%" y1="100%" x2="100%" y2="0%"><stop offset="0%" stop-color="#00D3E4"/><stop offset="60%" stop-color="#0094A0"/><stop offset="100%" stop-color="#007882"/></linearGradient></defs><circle cx="120" cy="120" r="116" fill="url(#oc)"/><circle cx="120" cy="120" r="116" fill="url(#or)"/><g transform="translate(20,40) scale(0.142)"><path d="M 0 900.84 C 532.341 651.368 841.069 454.81 1407.215 0 C 1190.699 365.98 1060.371 566.788 776.503 900.84 L 950.588 496.405 C 539.219 733.009 347.248 789.767 0 900.84 Z" fill="url(#og)"/></g></svg></div>';

function mediaHTML(rel, item, tag){
  if(item.img) return '<div class="media"><img src="'+rel+esc(item.img)+'" alt="" style="position:absolute;inset:0;width:100%;height:100%;object-fit:cover;">'+(tag?'<div class="m-tag">'+esc(tag)+'</div>':'')+'</div>';
  return '<div class="media '+(item.grad||'m-teal')+'">'+ORB+(tag?'<div class="m-tag">'+esc(tag)+'</div>':'')+'</div>';
}

/* Which public-nav destination lights up for a given emitted path. */
function navActiveFor(p){
  if(!p) return null;
  if(p.startsWith('events/')) return 'events';
  if(p.startsWith('library/')) return 'library';
  if(p.startsWith('labs/')) return 'labs';
  if(p.startsWith('projects/')||p.startsWith('pods/')||p.startsWith('people/')) return 'work';
  return null;
}
function crumbsHTML(rel, trail){
  // trail: [[label, href|null]...] — last item is the current page (no link)
  return '<div class="crumbs">'+trail.map(([l,h],i)=>{
    const piece=h?'<a href="'+h+'">'+esc(l)+'</a>':'<span>'+esc(l)+'</span>';
    return (i?'<span class="sep">/</span>':'')+piece;
  }).join('')+'</div>';
}
function upsellHTML(rel){
  return '<div class="upsell" id="pg-upsell" style="display:none;"><p>Find your people. Build your edge.</p><span class="t-small">Free to join · run in the open</span><a class="btn btn-red btn-sm" href="'+rel+'index.html">Create account</a></div>';
}


function shell(o){ // {rel, path, title, desc, ogType, crumbs, body, modals, pageJS, bodyStyle}
  return '<!DOCTYPE html>\n<html lang="en">\n'+MARK+'\n<head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">\n'
    +'<title>'+esc(o.title)+' · The Upskilling Labs</title>\n'
    +'<meta name="description" content="'+esc(o.desc)+'">\n'
    +'<link rel="canonical" href="'+SITE_BASE+'/'+o.path+'">\n'
    +'<meta property="og:title" content="'+esc(o.title)+'">\n'
    +'<meta property="og:description" content="'+esc(o.desc)+'">\n'
    +'<meta property="og:type" content="'+(o.ogType||'website')+'">\n'
    +'<meta property="og:url" content="'+SITE_BASE+'/'+o.path+'">\n'
    +'<meta property="og:image" content="'+SITE_BASE+'/assets/orb-mark.png">\n'
    +'<meta property="og:site_name" content="The Upskilling Labs">\n'
    +'<link rel="stylesheet" href="'+o.rel+'font.css">\n<link rel="stylesheet" href="'+o.rel+'tokens.css">\n<link rel="stylesheet" href="'+o.rel+'system.css">\n'
    +'</head>\n<body'+(o.bodyStyle?' style="'+o.bodyStyle+'"':'')+'>\n'
    +chrome.publicNavHTML(o.rel, navActiveFor(o.path))+'\n'
    +'<div class="container">'+crumbsHTML(o.rel,o.crumbs)+'</div>\n'
    +o.body+'\n'
    +chrome.footerHTML(o.rel)
    +upsellHTML(o.rel)
    +(o.modals||'')
    +'\n<script src="'+o.rel+'shared.js"></script>\n<script src="'+o.rel+'chrome.js"></script>\n<script>LabsChrome.wireNav();LabsChrome.sessionChrome();'+(o.pageJS||'')+'</script>\n'
    +'<script src="'+o.rel+'events/data.js"></script>\n<script src="'+o.rel+'library/data.js"></script>\n<script src="'+o.rel+'labs/data.js"></script>\n<script src="'+o.rel+'cycles/data.js"></script>\n<script src="'+o.rel+'projects/data.js"></script>\n<script src="'+o.rel+'pods/data.js"></script>\n<script src="'+o.rel+'people/data.js"></script>\n'
    +'<script>window.SEARCH_REL="'+o.rel+'";</script>\n<script src="'+o.rel+'search.js"></script>\n</body>\n</html>\n';
}

/* ── Teaser cards (the "card = metadata" contract; same shape as index.html's) ── */
function eventTeaser(rel, e){
  return '<a class="card tappable" href="'+rel+'events/'+e.slug+'/">'+mediaHTML(rel,e,e.kind||(e.location_type==='virtual'?'Virtual':'In person'))
    +'<div class="card-body"><div class="lbl lbl-teal">'+fmtDate(e.start_at)+'</div><div class="t-h4" style="margin:6px 0 4px;">'+esc(e.name)+'</div><p class="t-small">'+esc(e.location_name)+'</p></div></a>';
}
function resourceTeaser(rel, r){
  const typeLabel={guide:'Guide',recording:'Recording',template:'Template',course:'Course',playbook:'Playbook'}[r.content_type]||'Guide';
  return '<a class="card tappable" href="'+rel+'library/'+r.slug+'/">'+mediaHTML(rel,r,typeLabel)
    +'<div class="card-body"><div class="lbl lbl-teal">'+esc(r.meta||'')+'</div><div class="t-h4" style="margin:6px 0 4px;">'+esc(r.title)+'</div><p class="t-small">'+esc(r.summary||'')+'</p></div></a>';
}
function labTeaser(rel, m){
  const pill=m.status==='active'?'<span class="status active">Active</span>':'<span class="status forming">Waitlist open</span>';
  const sub=m.status==='active'?esc(m.partner)+' · '+m.members+' members':m.waiting+(m.waiting===1?' person':' people')+' waiting';
  return '<a class="card tappable" href="'+rel+'labs/'+m.slug+'/">'+mediaHTML(rel,m,m.slug==='dc'?'Flagship':'')
    +'<div class="card-body"><div class="card-row" style="margin-bottom:6px;">'+pill+'</div><div class="t-h4" style="margin-bottom:4px;">'+esc(m.name+(m.st&&m.slug!=='dc'?', '+m.st:''))+'</div><p class="t-small">'+sub+'</p></div></a>';
}
function relatedHTML(rel, title, teasers){
  if(!teasers.length) return '';
  // The landing's section-head component — eyebrow + rule — so recirculation reads as the same system.
  return '<section class="section"><div class="container"><div class="section-head"><div><div class="lbl lbl-teal" style="margin-bottom:8px;">More like this</div><h2 class="t-h3">'+esc(title)+'</h2></div></div><div class="cards dense">'+teasers.join('')+'</div></div></section>';
}

/* ── Event pages ── */
const RSVP_MODAL = (rel)=>`
<div class="gate-modal" id="rsvp-modal" onclick="if(event.target===this)closeRsvp()">
  <div class="gate-sheet">
    <button class="gate-close" onclick="closeRsvp()" aria-label="Close"><svg width="20" height="20" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M5 5L17 17M17 5L5 17" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg></button>
    <div id="rsvp-body">
      <h3 class="t-h3" style="margin-bottom:6px;">Save a spot</h3>
      <p class="t-body" id="rsvp-ctx" style="margin-bottom:16px;"></p>
      <input id="rsvp-email" type="email" placeholder="you@email.com" style="width:100%;border:1px solid var(--rule);border-radius:var(--r);padding:14px;font:inherit;font-size:16px;background:var(--white);margin-bottom:12px;">
      <button class="btn btn-teal btn-block" onclick="submitRsvp()">Save my spot</button>
      <p class="t-small" style="margin-top:12px;color:var(--meta);">Free and first come, first served — no account needed. We'll send the details.</p>
    </div>
    <div id="rsvp-done" style="display:none;text-align:center;padding:12px 0;">
      <h3 class="t-h3" style="margin-bottom:8px;">Spot saved ✓</h3>
      <p class="t-body" style="margin-bottom:16px;">Details are on their way to your inbox. See you there.</p>
      <button class="btn btn-ghost-teal btn-sm" onclick="closeRsvp()">Done</button>
    </div>
  </div>
</div>`;

function eventPage(e){
  const rel='../../';
  const slides=(e.img?['IMG']:[]).concat(e.gallery||['m-teal','m-forest','m-navy']).slice(0,3);
  const gallery='<div class="gallery"><div class="gallery-track" id="ev-gallery">'
    +slides.map(g=>g==='IMG'
      ?'<div class="media"><img src="'+rel+esc(e.img)+'" alt="" style="position:absolute;inset:0;width:100%;height:100%;object-fit:cover;"></div>'
      :'<div class="media '+g+'">'+ORB+'</div>').join('')
    +'</div><div class="gallery-dots" id="ev-dots">'+slides.map((_,i)=>'<i'+(i?'':' class="on"')+'></i>').join('')+'</div></div>';
  const kv=(k,v)=>'<div class="kv"><span class="k lbl">'+k+'</span><span class="t-body">'+esc(v)+'</span></div>';
  const others=EVENTS.filter(x=>x.slug!==e.slug && new Date(x.start_at)>=new Date(e.start_at)).slice(0,3);
  const related=others.length?others:EVENTS.filter(x=>x.slug!==e.slug).slice(-3);
  const body='<div class="container"><div class="detail" style="margin-top:16px;">'
    +'<div class="detail-main">'+gallery
    +'<div style="display:flex;gap:10px;align-items:center;margin-top:20px;"><span class="lbl lbl-teal">'+fmtDate(e.start_at)+'</span><span class="lbl">'+(e.location_type==='virtual'?'Virtual':'In person')+(e.kind?' · '+esc(e.kind):'')+'</span></div>'
    +'<h1 class="t-h1">'+esc(e.name)+'</h1>'
    +'<p class="t-lede" style="margin-bottom:20px;">'+esc(e.desc)+'</p>'
    +(e.body||[]).map(p=>'<p class="t-body" style="margin-bottom:14px;">'+esc(p)+'</p>').join('')
    +'<div style="margin-top:24px;">'
    +kv('Where', e.location_name)
    +kv('When', fmtDay(e.start_at)+' · '+fmtTime(e.start_at)+(e.end_at?'–'+fmtTime(e.end_at):''))
    +kv('Cost', e.cost||'Free')
    +kv('Host', e.host||'The Upskilling Labs')
    +(e.bring?kv('Bring', e.bring):'')
    +'</div>'
    +'<div class="detail-bottom"><button class="btn btn-red btn-block" onclick="openRsvp()">Register — save a spot</button></div>'
    +'</div>'
    +'<aside class="detail-aside"><div class="lcard" style="padding:24px;">'
    +'<div class="t-h3" style="margin-bottom:4px;">'+esc(e.cost||'Free')+'</div><p class="t-small" style="margin-bottom:16px;">per person · first come, first served</p>'
    +'<p class="t-body" style="margin-bottom:16px;">'+fmtDay(e.start_at)+'<br>'+fmtTime(e.start_at)+(e.end_at?'–'+fmtTime(e.end_at):'')+' · '+esc(e.location_name)+'</p>'
    +'<button class="btn btn-red btn-block" onclick="openRsvp()">Register — save a spot</button>'
    +'<p class="t-small" style="margin-top:12px;">'+(e.location_type==='virtual'?"Online — we'll send the link.":"Free & public — we'll send the room details.")+'</p>'
    +'</div></aside>'
    +'</div></div>'
    +relatedHTML(rel,'More sessions like this', related.map(x=>eventTeaser(rel,x)));
  const pageJS=`
function openRsvp(){ document.getElementById('rsvp-ctx').textContent='Saving your spot for ${e.name.replace(/'/g,"\\'")} — ${fmtDate(e.start_at).replace(/'/g,"\\'")}.'; var em=document.getElementById('rsvp-email'); if(window.LABS_SESSION&&LABS_SESSION.signedIn&&!em.value) em.value='alex.rivera@gmail.com'; document.getElementById('rsvp-body').style.display='block'; document.getElementById('rsvp-done').style.display='none'; document.getElementById('rsvp-modal').classList.add('open'); em.focus(); }
function submitRsvp(){ var em=document.getElementById('rsvp-email'); if(!/^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$/.test(em.value.trim())){ em.style.borderColor='var(--red)'; em.focus(); return; } document.getElementById('rsvp-body').style.display='none'; document.getElementById('rsvp-done').style.display='block'; }
function closeRsvp(){ document.getElementById('rsvp-modal').classList.remove('open'); }
document.addEventListener('keydown',function(e){ if(e.key==='Escape') closeRsvp(); });
(function(){ var t=document.getElementById('ev-gallery'), d=document.getElementById('ev-dots'); if(!t||!d) return;
  t.addEventListener('scroll',function(){ var i=Math.round(t.scrollLeft/t.clientWidth); [].forEach.call(d.children,function(el,j){ el.className=j===i?'on':''; }); },{passive:true}); })();`;
  return shell({ rel, path:'events/'+e.slug+'/', title:e.name, desc:e.desc, ogType:'article',
    crumbs:[['Home',rel+'index.html'],['Events','../'],[e.name,null]], body, modals:RSVP_MODAL(rel), pageJS });
}

/* ── Resource pages ── */
function resourcePage(r){
  const rel='../../';
  const typeLabel={guide:'Guide',recording:'Recording',template:'Template',course:'Course',playbook:'Playbook'}[r.content_type]||'Guide';
  const related=RESOURCES.filter(x=>x.slug!==r.slug&&x.status==='published'&&(x.tags||[]).some(t=>(r.tags||[]).includes(t))).slice(0,3);
  const fill=related.length<3?RESOURCES.filter(x=>x.slug!==r.slug&&x.status==='published'&&!related.includes(x)).slice(0,3-related.length):[];
  const body='<div class="container"><div class="detail" style="margin-top:16px;">'
    +'<div class="detail-main">'+mediaHTML(rel,r,typeLabel)
    +'<div style="display:flex;gap:10px;align-items:center;margin-top:20px;"><span class="lbl lbl-teal">'+esc(typeLabel)+'</span><span class="lbl">'+esc(r.meta||'')+'</span></div>'
    +'<h1 class="t-h1">'+esc(r.title)+'</h1>'
    +'<p class="t-lede" style="margin-bottom:20px;">'+esc(r.summary||'')+'</p>'
    +(r.body||[]).map(p=>'<p class="t-body" style="margin-bottom:14px;">'+esc(p)+'</p>').join('')
    +(r.from?'<div class="lcard" style="padding:18px 20px;margin-top:24px;border-left:3px solid var(--teal);"><div class="lbl lbl-teal" style="margin-bottom:6px;">From the commons</div><p class="t-body">'+esc(r.from)+'</p><p class="t-small" style="margin-top:6px;">Built in a cycle, returned to everyone — MIT code · CC BY 4.0 content, yours to build on.</p></div>':'')
    +'<div class="detail-bottom"><a class="btn btn-teal btn-block" href="'+esc(r.url||'#')+'">'+(r.content_type==='recording'?'Watch now':r.content_type==='course'?'Start the course':'Open it')+'</a></div>'
    +'</div>'
    +'<aside class="detail-aside"><div class="lcard" style="padding:24px;">'
    +'<div class="t-h3" style="margin-bottom:4px;">Free</div><p class="t-small" style="margin-bottom:16px;">'+esc(r.meta||'')+'</p>'
    +'<a class="btn btn-teal btn-block" href="'+esc(r.url||'#')+'">'+(r.content_type==='recording'?'Watch now':r.content_type==='course'?'Start the course':'Open it')+'</a>'
    +'<div style="margin-top:16px;">'
    +'<div class="kv"><span class="k lbl">By</span><span class="t-small">'+esc(r.author||'The Upskilling Labs')+'</span></div>'
    +'<div class="kv"><span class="k lbl">License</span><span class="t-small">'+esc(r.license||'CC BY 4.0')+'</span></div>'
    +'</div></div></aside>'
    +'</div></div>'
    +relatedHTML(rel,'More from the library', related.concat(fill).map(x=>resourceTeaser(rel,x)));
  return shell({ rel, path:'library/'+r.slug+'/', title:r.title, desc:r.summary||'', ogType:'article',
    crumbs:[['Home',rel+'index.html'],['Library','../'],[r.title,null]], body });
}

/* ── Lab pages ── */
function labPage(m){
  const rel='../../';
  const title=m.name+(m.st&&m.slug!=='dc'?', '+m.st:'');
  let body, pageJS='';
  if(m.status==='active'){
    body='<section class="grain" style="background:var(--ink);color:#fff;border-radius:var(--r);margin:16px var(--pad) 0;"><div style="max-width:720px;margin:0 auto;padding:56px 24px;">'
      +'<span class="status active" style="color:#fff;">Active lab</span>'
      +'<h1 class="t-h1" style="margin:14px 0 10px;color:#fff;">'+esc(m.name)+'</h1>'
      +'<p class="t-lede" style="color:var(--od2);margin-bottom:24px;">'+esc(m.blurb||'')+'</p>'
      +'<div style="display:flex;gap:32px;flex-wrap:wrap;margin-bottom:28px;">'
      +'<div><div class="t-h2" style="color:#fff;">'+m.members+'</div><div class="t-small" style="color:var(--od2);">members</div></div>'
      +'<div><div class="t-h2" style="color:#fff;">'+esc(m.partner||'')+'</div><div class="t-small" style="color:var(--od2);">library partner</div></div>'
      +'<div><div class="t-h2" style="color:#fff;">Summer 2026</div><div class="t-small" style="color:var(--od2);">Civic &amp; Elections Cycle in progress</div></div>'
      +'</div>'
      +'<a class="btn btn-white" href="'+rel+'index.html">Join this lab</a>'
      +'</div></section>'
      +'<section class="section"><div class="container"><div class="lbl lbl-teal" style="margin-bottom:8px;">The rhythm</div>'
      +'<div class="kv"><span class="k lbl">Weekly</span><span class="t-body">Workshops and build nights at the library</span></div>'
      +'<div class="kv"><span class="k lbl">Monthly</span><span class="t-body">Community showcase — real work, honest lessons</span></div>'
      +'<div class="kv"><span class="k lbl">Quarterly</span><span class="t-body">A Build Cycle: real problems, real teams, everything returned to the commons</span></div>'
      +'</div></section>'
      +relatedHTML(rel,'Upcoming at this lab', EVENTS.slice(0,3).map(x=>eventTeaser(rel,x)));
  } else {
    const waitingLine=m.waiting+(m.waiting===1?' person is':' people are')+' waiting';
    const otherWaits=Object.values(METROS).filter(x=>x.status==='waitlist'&&x.slug!==m.slug).sort((a,b)=>b.waiting-a.waiting).slice(0,3);
    body='<div class="container"><div class="detail" style="margin-top:16px;">'
      +'<div class="detail-main">'+mediaHTML(rel,m,'Waitlist')
      +'<div style="display:flex;gap:10px;align-items:center;margin-top:20px;"><span class="status forming">Waitlist open</span><span class="lbl">'+waitingLine+'</span></div>'
      +'<h1 class="t-h1">We’re not in '+esc(m.name)+' yet.</h1>'
      +'<p class="t-lede" style="margin-bottom:20px;">'+esc(m.blurb||'Every lab started as a list of names. Enough names, and we come.')+'</p>'
      +'<div class="lbl lbl-teal" style="margin:24px 0 4px;">What a lab is</div>'
      +'<div class="kv"><span class="k lbl">A place</span><span class="t-body">A library-hosted space'+(m.partner?' — '+esc(m.partner)+' is already at the table':'')+'</span></div>'
      +'<div class="kv"><span class="k lbl">A rhythm</span><span class="t-body">Weekly workshops, build nights, a monthly showcase</span></div>'
      +'<div class="kv"><span class="k lbl">A cycle</span><span class="t-body">When the list is long enough, a Build Cycle ignites — real problems, real teams, run in the open</span></div>'
      +'<p class="t-body" style="margin-top:20px;">Every lab started as a list of names. Enough names, and we come. The list is how we pick the next city — and your name moves it.</p>'
      +'<div class="detail-bottom"><a class="btn btn-red btn-block" id="wl-cta" href="'+rel+'index.html?join='+m.slug+'">Join the '+esc(m.name)+' waitlist</a></div>'
      +'</div>'
      +'<aside class="detail-aside"><div class="lcard" style="padding:24px;">'
      +'<div class="t-h3" style="margin-bottom:4px;">'+m.waiting+' waiting</div><p class="t-small" style="margin-bottom:16px;">One tap. One email when it happens. That’s it.</p>'
      +'<a class="btn btn-red btn-block" id="wl-cta-aside" href="'+rel+'index.html?join='+m.slug+'">Join the '+esc(m.name)+' waitlist</a>'
      +'<p class="t-small" style="margin-top:12px;">Takes a free account — sign in with Google and your name goes on the list.</p>'
      +'</div></aside>'
      +'</div></div>'
      +relatedHTML(rel,'Other cities lining up', otherWaits.map(x=>labTeaser(rel,x)))
      +relatedHTML(rel,'Meanwhile, in the Labs network', EVENTS.filter(e=>e.location_type==='virtual').slice(0,3).map(x=>eventTeaser(rel,x)));
    pageJS=`
(function(){ if(window.LABS_SESSION&&LABS_SESSION.signedIn&&(LABS_SESSION.waitlists||[]).indexOf('${m.slug}')>-1){
  ['wl-cta','wl-cta-aside'].forEach(function(id){ var el=document.getElementById(id); if(el){ el.textContent='You’re on the list ✓'; el.classList.remove('btn-red'); el.classList.add('btn-ghost-teal'); el.removeAttribute('href'); el.style.pointerEvents='none'; } }); } })();`;
  }
  return shell({ rel, path:'labs/'+m.slug+'/', title:title+' — Local lab', desc:m.status==='active'?(m.blurb||''):(m.waiting+' people want a '+m.name+' lab. Add your name — we’ll email you the day it ignites.'), ogType:'website',
    crumbs:[['Home',rel+'index.html'],['Local labs','../'],[title,null]], body, pageJS });
}

/* ── Directory pages ── */
function directoryPage(type){
  const rel='../';
  if(type==='events'){
    const list=EVENTS.slice().sort((a,b)=>new Date(a.start_at)-new Date(b.start_at));
    return shell({ rel, path:'events/', title:'Events & workshops', desc:'Free, public, hands-on. Drop into a session — or into the cycle’s six anchor events.',
      crumbs:[['Home',rel+'index.html'],['Events',null]],
      body:'<section class="section"><div class="container"><div class="section-head"><div><div class="lbl lbl-teal" style="margin-bottom:8px;">Events & workshops · '+list.length+'</div><h1 class="t-h2">Drop into a session</h1></div></div><p class="t-lede" style="margin-bottom:28px;">Free and public, every one. ✦ marks the cycle’s six anchor events.</p><div class="cards dense all">'+list.map(e=>eventTeaser(rel,e)).join('')+'</div></div></section>' });
  }
  if(type==='library'){
    const list=RESOURCES.filter(r=>r.status==='published');
    return shell({ rel, path:'library/', title:'Learning Library', desc:'Guides, recordings, templates, and playbooks — including work returned to the commons by cycle teams.',
      crumbs:[['Home',rel+'index.html'],['Library',null]],
      body:'<section class="section"><div class="container"><div class="section-head"><div><div class="lbl lbl-teal" style="margin-bottom:8px;">Learning Library · '+list.length+'</div><h1 class="t-h2">Learn by doing</h1></div></div><p class="t-lede" style="margin-bottom:28px;">Everything here is free and open — including what cycle teams returned to the commons.</p><div class="cards dense all">'+list.map(r=>resourceTeaser(rel,r)).join('')+'</div></div></section>' });
  }
  const list=Object.values(METROS).sort((a,b)=>(a.status==='active'?-1:b.status==='active'?1:b.waiting-a.waiting));
  return shell({ rel, path:'labs/', title:'Local labs', desc:'One lab is live. Every other city starts as a list of names — find yours, or start it.',
    crumbs:[['Home',rel+'index.html'],['Local labs',null]],
    body:'<section class="section"><div class="container"><div class="section-head"><div><div class="lbl lbl-teal" style="margin-bottom:8px;">Local labs · library-hosted</div><h1 class="t-h2">Find your city</h1></div></div><p class="t-lede" style="margin-bottom:28px;">One lab is live. Every other city starts as a list of names. Find yours — or start it.</p><div class="cards dense all">'+list.map(m=>labTeaser(rel,m)).join('')+'</div>'
    +'<div class="lcard" style="padding:24px;margin-top:32px;display:flex;gap:16px;align-items:center;justify-content:space-between;flex-wrap:wrap;"><div><div class="t-h4" style="margin-bottom:4px;">Don’t see your city?</div><p class="t-small">Search any city — or be the first name on its list.</p></div><a class="btn btn-ghost-teal btn-sm" href="'+rel+'index.html#sec-labs">Search your city</a></div>'
    +'</div></section>' });
}


/* ── Static pages: About + the public Build Cycles page ── */
function darkHero(inner){ return '<section class="grain" style="background:var(--ink);color:#fff;"><div class="container" style="max-width:760px;padding-top:56px;padding-bottom:56px;">'+inner+'</div></section>'; }
function eyebrow(t){ return '<div class="lbl lbl-teal" style="margin-bottom:12px;">'+esc(t)+'</div>'; }
function pullQuote(t){ return '<p style="font-size:24px;font-weight:600;line-height:34px;letter-spacing:-.02em;color:var(--ink);border-left:2px solid var(--teal);padding-left:24px;margin-bottom:56px;">'+t+'</p>'; }

function aboutPage(){
  const rel='../';
  const body=darkHero(
     '<div class="lbl lbl-teal" style="margin-bottom:16px;">About</div>'
    +'<h1 class="t-h1" style="max-width:24ch;">We believe people are capable of far more than they&rsquo;ve been given the opportunity to prove.</h1>'
    +'<p class="t-lede" style="margin-top:18px;max-width:52ch;color:var(--od2);">The world has changed. Knowledge is everywhere. AI is transforming how work gets done. Careers are becoming less predictable, more interdisciplinary, and more self-directed.</p>'
    +'<p class="t-lede" style="margin-top:14px;max-width:52ch;color:var(--od2);">The challenge isn&rsquo;t keeping up with information. It&rsquo;s becoming the kind of person who can make sense of change &mdash; and help shape what comes next.</p>'
    +'<p class="t-lede" style="margin-top:14px;max-width:52ch;color:var(--od1);font-weight:600;">That&rsquo;s why The Upskilling Labs exists.</p>')
  +'<div class="container" style="padding-top:56px;padding-bottom:24px;max-width:760px;">'
    +eyebrow('Our perspective')
    +'<h2 class="t-h2" style="margin-bottom:16px;">The way we learn hasn&rsquo;t kept pace with the world.</h2>'
    +'<p class="t-lede" style="margin-bottom:16px;">Knowledge used to be the hard part. Now it&rsquo;s everywhere, and AI is putting expertise within anyone&rsquo;s reach. The skills that matter change faster every year.</p>'
    +'<p class="t-body" style="margin-bottom:28px;">What work rewards now is different: curiosity, judgment, collaboration, and the ability to adapt. The future belongs to people who keep growing what they&rsquo;re capable of.</p>'
    +pullQuote('We don&rsquo;t think the answer is more information. We think it&rsquo;s learning that becomes capability.')
    +eyebrow('What we believe')
    +'<h2 class="t-h2" style="margin-bottom:16px;">Capability changes everything.</h2>'
    +'<p class="t-lede" style="margin-bottom:20px;">Principles, not programs:</p>'
    +'<div style="margin-bottom:56px;">'
    +['People are more capable than they realize.','Capability grows through practice.','Confidence is earned through experience.','Better questions matter more than faster answers.','Communities become stronger when more people can contribute meaningfully.','Learning never really ends.'].map(b=>'<div class="kv"><span class="t-body">'+b+'</span></div>').join('')
    +'</div>'
    +eyebrow('What we built')
    +'<h2 class="t-h2" style="margin-bottom:16px;">So we built a different kind of place.</h2>'
    +'<p class="t-lede" style="margin-bottom:24px;">The Upskilling Labs is a community built around a simple idea: learning sticks when you use it. You learn, you practice, you build &mdash; together. Born at DC Public Library in fall 2025, run in the open ever since.</p>'
    +'<div class="cards two" style="margin-bottom:56px;">'
    +[['Build Cycles','Thirteen weeks, a real problem, a small team that ships.'],['Pods','A handful of people who dig into a problem together.'],['Workshops','Hands-on sessions led by practitioners, open to everyone.'],['Mentors','People who&rsquo;ve done the work, around when you&rsquo;re stuck.'],['Community','Library-hosted, in person, in the open.'],['AI','A tool we use everywhere. Never the destination.']].map(([t,b])=>'<div class="lcard" style="padding:22px;"><div class="lbl lbl-teal" style="margin-bottom:8px;">'+t+'</div><p class="t-small">'+b+'</p></div>').join('')
    +'</div>'
    +eyebrow('What happens here')
    +'<h2 class="t-h2" style="margin-bottom:16px;">Transformation happens through practice.</h2>'
    +'<p class="t-lede" style="margin-bottom:20px;">You might&hellip;</p>'
    +'<div style="margin-bottom:28px;">'
    +['investigate a real problem','interview the people living it','prototype an idea','work alongside people outside your field','experiment with emerging technology','present your work publicly','discover strengths you didn&rsquo;t know you had'].map(b=>'<div class="kv"><span class="t-body">'+b+'</span></div>').join('')
    +'</div>'
    +pullQuote('You leave more capable than you arrived.')
    +eyebrow('Who belongs here')
    +'<h2 class="t-h2" style="margin-bottom:16px;">You don&rsquo;t need to have it all figured out.</h2>'
    +'<p class="t-lede" style="margin-bottom:20px;">Not credentials. Not a profession. A mindset. The people who thrive here are&hellip;</p>'
    +'<div style="display:flex;flex-wrap:wrap;gap:8px;margin-bottom:20px;">'
    +['curious','generous','intellectually humble','willing to experiment','excited by difficult problems','comfortable learning in public'].map(t=>'<span class="chip" style="cursor:default;">'+t+'</span>').join('')
    +'</div>'
    +'<p class="t-body" style="font-weight:600;margin-bottom:56px;">If you&rsquo;re willing to grow, you belong here.</p>'
    +eyebrow('Looking forward')
    +'<h2 class="t-h2" style="margin-bottom:16px;">We&rsquo;re building for a future none of us can predict.</h2>'
    +'<p class="t-lede" style="margin-bottom:16px;">The Labs isn&rsquo;t preparing you for one job or one technology. It&rsquo;s how you build the capacity to navigate change &mdash; this year&rsquo;s, and every year after.</p>'
    +'<p class="t-body" style="margin-bottom:56px;">That&rsquo;s the mission. Not preparing people for the future. Helping people become the kind of people who can help create it.</p>'
    +'<h2 class="t-h2" style="margin-bottom:16px;">This is just the beginning.</h2>'
    +'<p class="t-lede" style="margin-bottom:24px;">Whether you&rsquo;re looking to challenge yourself, contribute to something meaningful, meet extraordinary people, or simply become more capable than you were yesterday, there&rsquo;s a place for you here.</p>'
    +'<a class="btn btn-red btn-lg" href="'+rel+'cycles/index.html">Explore how The Labs works</a>'
    +'<p style="margin-top:16px;margin-bottom:32px;"><a class="see" href="'+rel+'index.html">Ready now? Join The Labs &rarr;</a></p>'
  +'</div>';
  return shell({ rel, path:'about/', title:'About', desc:'We believe people are capable of far more than they’ve been given the opportunity to prove. That’s why The Upskilling Labs exists.',
    crumbs:[['Home',rel+'index.html'],['About',null]], body });
}

function cyclesPage(){
  const rel='../';
  const c=CYCLE_PUBLIC;
  const anchors=EVENTS.filter(e=>e.anchor);
  const shipped=APPROVED_PROJECTS.slice(0,2);
  const body=darkHero(
     '<div class="lbl lbl-teal" style="margin-bottom:16px;">Build Cycles · 4 a year</div>'
    +'<h1 class="t-h1" style="max-width:22ch;">Thirteen weeks from now, you&rsquo;ll have built something real.</h1>'
    +'<p class="t-lede" style="margin-top:18px;max-width:52ch;color:var(--od2);">You&rsquo;ll pick a problem that matters to you, team up, and see it through &mdash; with mentors and a whole community behind you.</p>'
    +'<div style="margin-top:28px;"><a class="btn btn-red btn-lg" href="'+rel+'index.html?register=cycle">Register for this cycle</a></div>')
  +'<div class="container" style="padding-top:56px;padding-bottom:24px;max-width:760px;">'
    +'<div class="cards two" style="margin-bottom:56px;">'
    +[['What you walk away with','Something real you helped build, proof of it on your profile, and people who&rsquo;ve seen what you can do.'],['How you get there','Month one: dig into a real problem with your pod. Month two: decide what to build at the Hackathon. Month three: build it, test it, and show it.'],['What it takes','Six in-person events, a five-minute check-in each week, and the rest on your own time with your team.'],['Open source, on purpose','Everything a team builds here is an open-source community project. When the cycle&rsquo;s over, you&rsquo;re free to do whatever you want with it &mdash; and so is everyone else.']].map(([t,b])=>'<div class="lcard" style="padding:22px;"><div class="lbl lbl-teal" style="margin-bottom:8px;">'+t+'</div><p class="t-small">'+b+'</p></div>').join('')
    +'</div>'
    +eyebrow('The current cycle')
    +'<h2 class="t-h2" style="margin-bottom:16px;">'+esc(c.theme)+' &middot; '+esc(c.name)+'</h2>'
    +'<p class="t-lede" style="margin-bottom:24px;">'+esc(c.city)+' &middot; Kickoff '+fmtDay(c.kickoff)+' &middot; '+c.weeks+' weeks &middot; An Open Cycle &mdash; every project is open source.</p>'
    +'<div class="lcard" style="padding:22px 24px;margin-bottom:56px;">'
    +'<div class="lbl lbl-teal" style="margin-bottom:8px;">The six anchor events</div>'
    +anchors.map(e=>'<div class="kv"><span class="k lbl" style="width:110px;">'+fmtDate(e.start_at)+'</span><span class="t-body">✦ <a href="'+rel+'events/'+e.slug+'/" style="color:inherit;">'+esc(e.name)+'</a><span class="t-small" style="color:var(--meta);"> &middot; '+esc(e.location_name)+'</span></span></div>').join('')
    +'</div>'
    +eyebrow('How it works')
    +'<h2 class="t-h2" style="margin-bottom:16px;">Three phases, one arc.</h2>'
    +'<div class="cards two" style="margin-bottom:56px;">'
    +['problem','frame','building'].map(k=>{const ph=c.phaseInfo[k];return '<div class="lcard" style="padding:22px;"><div class="lbl lbl-teal" style="margin-bottom:8px;">'+esc(ph.title)+' &middot; '+esc(ph.when)+'</div><p class="t-small">'+esc(ph.body)+'</p></div>';}).join('')
    +'</div>'
    +eyebrow('What this cycle is working on')
    +'<h2 class="t-h2" style="margin-bottom:16px;">Real problems, brought by real partners.</h2>'
    +'<div style="margin-bottom:56px;">'
    +SITUATIONS.map(si=>'<div class="kv"><span class="t-body">'+esc(si.title)+'<span class="t-small" style="color:var(--meta);"> &middot; Brought by '+esc(si.owner)+'</span></span></div>').join('')
    +'</div>'
    +(shipped.length?(eyebrow('What past cycles shipped')
      +'<h2 class="t-h2" style="margin-bottom:20px;">The proof is public.</h2>'
      +'<div class="cards two" style="margin-bottom:32px;">'+shipped.map(pr=>projectTeaser(rel,pr)).join('')+'</div>'
      +'<p style="margin-bottom:56px;"><a class="see" href="'+rel+'projects/index.html">All projects &rarr;</a></p>'):'')
    +'<h2 class="t-h2" style="margin-bottom:16px;">Ready?</h2>'
    +'<p class="t-lede" style="margin-bottom:24px;">Registration takes a few minutes. The commitment is real, and so is what you&rsquo;ll build.</p>'
    +'<a class="btn btn-red btn-lg" href="'+rel+'index.html?register=cycle">Register for this cycle</a>'
    +'<p style="margin-top:16px;margin-bottom:32px;"><a class="see" href="'+rel+'events/'+anchors[0].slug+'/">Just curious? Come to Kickoff &rarr;</a></p>'
  +'</div>';
  return shell({ rel, path:'cycles/', title:'Build Cycles', desc:'Thirteen weeks from now, you’ll have built something real. Pick a problem, team up, and see it through — in the open.',
    crumbs:[['Home',rel+'index.html'],['Build Cycles',null]], body });
}

/* ── The public Work layer: projects, pods, people (public by artifact, private by process) ── */
function projectTeaser(rel, pr){
  return '<a class="card tappable" href="'+rel+'projects/'+pr.slug+'/">'+mediaHTML(rel,{grad:pr.grad},pr.cycle.split(' · ')[0])
    +'<div class="card-body"><div class="lbl lbl-teal">'+esc(pr.cycle)+'</div><div class="t-h4" style="margin:6px 0 4px;">'+esc(pr.title)+'</div><p class="t-small">'+esc(pr.summary)+'</p></div></a>';
}
function podTeaser(rel, pd){
  const pill=pd.status==='shipped'?'<span class="status active">Shipped</span>':pd.status==='forming'?'<span class="status forming">Forming</span>':'<span class="status active">Open</span>';
  return '<a class="card tappable" href="'+rel+'pods/'+pd.slug+'/">'+mediaHTML(rel,{grad:pd.status==='shipped'?'m-navy':'m-forest'},'')
    +'<div class="card-body"><div class="card-row" style="margin-bottom:6px;">'+pill+'</div><div class="t-h4" style="margin-bottom:4px;">'+esc(pd.name)+'</div><p class="t-small">'+esc(pd.focus)+'</p></div></a>';
}
function personTeaser(rel, m){
  return '<a class="card tappable" href="'+rel+'people/'+m.handle+'/"><div class="card-body"><div style="display:flex;align-items:center;gap:14px;">'
    +'<span style="width:52px;height:52px;border-radius:50%;background:var(--teal-deep);color:#fff;display:flex;align-items:center;justify-content:center;font-weight:700;font-size:18px;flex-shrink:0;">'+esc(m.name.split(' ').map(w=>w[0]).join(''))+'</span>'
    +'<div><div class="t-h4">'+esc(m.name)+(m.verified?' <span title="Vouched for by The Labs" style="color:var(--teal-deep);">✓</span>':'')+'</div><p class="t-small" style="color:var(--teal-deep);font-weight:600;">'+esc(m.headline)+'</p></div></div></div></a>';
}
function bylineHTML(rel, team){
  return team.map(t=>t.handle?'<a href="'+rel+'people/'+t.handle+'/" style="color:var(--teal-deep);font-weight:600;">'+esc(t.name)+'</a>'+(t.role?' <span class="t-small" style="color:var(--meta);">('+esc(t.role)+')</span>':''):esc(t.name)).join(', ');
}
function projectPage(pr){
  const rel='../../';
  const pod=PODS.find(x=>x.slug===pr.pod);
  const others=APPROVED_PROJECTS.filter(x=>x.slug!==pr.slug).slice(0,2);
  const body='<div class="container" style="padding-top:16px;padding-bottom:24px;max-width:760px;">'
    +mediaHTML(rel,{grad:pr.grad},pr.cycle.split(' · ')[0])
    +'<div style="margin-top:20px;"><span class="lbl lbl-teal">'+esc(pr.cycle)+'</span></div>'
    +'<h1 class="t-h1" style="margin:8px 0 10px;">'+esc(pr.title)+'</h1>'
    +'<p class="t-lede" style="margin-bottom:20px;">'+esc(pr.summary)+'</p>'
    +pullQuote(esc(pr.frame))
    +eyebrow('The problem')+'<p class="t-body" style="margin-bottom:28px;">'+esc(pr.problem||'')+'</p>'
    +(pr.body||[]).map(x=>'<p class="t-body" style="margin-bottom:14px;">'+esc(x)+'</p>').join('')
    +'<div style="margin-top:28px;margin-bottom:40px;">'
    +'<div class="kv"><span class="k lbl">Outcome</span><span class="t-body">'+esc(pr.outcome||'')+'</span></div>'
    +'<div class="kv"><span class="k lbl">Team</span><span class="t-body">'+bylineHTML(rel,pr.team||[])+'</span></div>'
    +(pod?'<div class="kv"><span class="k lbl">Pod</span><span class="t-body"><a href="'+rel+'pods/'+pod.slug+'/" style="color:var(--teal-deep);font-weight:600;">'+esc(pod.name)+'</a></span></div>':'')
    +((pr.commons||[]).length?'<div class="kv"><span class="k lbl">Commons</span><span class="t-body">'+pr.commons.map(cm=>'<a href="'+rel+'library/'+cm.slug+'/" style="color:var(--teal-deep);font-weight:600;">'+esc(cm.title)+'</a>').join(' · ')+' <span class="t-small" style="color:var(--meta);">— free for anyone to use and build on</span></span></div>':'')
    +'</div></div>'
    +(others.length?relatedHTML(rel,'More shipped projects',others.map(x=>projectTeaser(rel,x))):'');
  return shell({ rel, path:'projects/'+pr.slug+'/', title:pr.title, desc:pr.summary, ogType:'article',
    crumbs:[['Home',rel+'index.html'],['Projects','../'],[pr.title,null]], body });
}
function podPage(pd){
  const rel='../../';
  const projs=APPROVED_PROJECTS.filter(x=>(pd.projects||[]).includes(x.slug));
  const pill=pd.status==='shipped'?'<span class="status active">Shipped</span>':pd.status==='forming'?'<span class="status forming">Forming</span>':'<span class="status active">Open now</span>';
  const body='<div class="container" style="padding-top:16px;padding-bottom:24px;max-width:760px;">'
    +'<div style="display:flex;gap:10px;align-items:center;margin-bottom:8px;">'+pill+'<span class="lbl">'+esc(pd.cycle)+'</span></div>'
    +'<h1 class="t-h1" style="margin-bottom:10px;">'+esc(pd.name)+'</h1>'
    +'<p class="t-lede" style="margin-bottom:24px;">'+esc(pd.focus)+'</p>'
    +(pd.story?'<p class="t-body" style="margin-bottom:28px;">'+esc(pd.story)+'</p>':'')
    +'<div style="margin-bottom:40px;">'
    +'<div class="kv"><span class="k lbl">Members</span><span class="t-body">'+pd.members+((pd.team||[]).length?' — including '+bylineHTML(rel,pd.team):'')+'</span></div>'
    +(pd.meets?'<div class="kv"><span class="k lbl">Meets</span><span class="t-body">'+esc(pd.meets)+'</span></div>':'')
    +'</div>'
    +(projs.length?(eyebrow('What this pod shipped')+'<div class="cards two" style="margin-bottom:40px;">'+projs.map(x=>projectTeaser(rel,x)).join('')+'</div>'):'')
    +(pd.status!=='shipped'?'<div class="lcard" style="padding:24px;margin-bottom:32px;"><div class="t-h4" style="margin-bottom:6px;">Want in?</div><p class="t-small" style="margin-bottom:16px;">Pods are how cycle members work. Register for the cycle, then pick your pod.</p><a class="btn btn-red" href="'+rel+'index.html?register=cycle">Register for the cycle</a></div>':'')
    +'</div>';
  return shell({ rel, path:'pods/'+pd.slug+'/', title:pd.name, desc:pd.focus,
    crumbs:[['Home',rel+'index.html'],['Pods','../'],[pd.name,null]], body });
}
function personPage(m){
  const rel='../../';
  const projs=APPROVED_PROJECTS.filter(x=>(m.projects||[]).includes(x.slug));
  const body='<div class="container" style="padding-top:16px;padding-bottom:24px;max-width:760px;">'
    +'<div style="display:flex;align-items:center;gap:20px;margin-bottom:20px;">'
    +'<span style="width:84px;height:84px;border-radius:50%;background:var(--teal-deep);color:#fff;display:flex;align-items:center;justify-content:center;font-weight:700;font-size:28px;flex-shrink:0;">'+esc(m.name.split(' ').map(w=>w[0]).join(''))+'</span>'
    +'<div><h1 class="t-h1" style="margin-bottom:4px;">'+esc(m.name)+'</h1>'
    +'<p class="t-lede" style="color:var(--teal-deep);font-weight:600;">'+esc(m.headline)+'</p></div></div>'
    +(m.verified?'<p style="margin-bottom:16px;"><span class="status active">✓ Vouched by The Labs</span></p>':'')
    +'<p class="t-body" style="margin-bottom:20px;">'+esc(m.bio||'')+'</p>'
    +'<div style="display:flex;flex-wrap:wrap;gap:8px;margin-bottom:12px;">'+(m.expertise||[]).map(t=>'<span class="chip" style="cursor:default;">'+esc(t)+'</span>').join('')+'</div>'
    +'<p class="t-small" style="color:var(--meta);margin-bottom:40px;">'+esc(m.city||'')+'</p>'
    +(projs.length?(eyebrow('Public work')+'<div class="cards two" style="margin-bottom:40px;">'+projs.map(x=>projectTeaser(rel,x)).join('')+'</div>'):'')
    +'<p class="t-small" style="color:var(--meta);margin-bottom:32px;">Public portfolios are opt-in. Members control what shows here — the full profile lives inside The Labs.</p>'
    +'</div>';
  return shell({ rel, path:'people/'+m.handle+'/', title:m.name, desc:m.headline, ogType:'profile',
    crumbs:[['Home',rel+'index.html'],['People','../'],[m.name,null]], body });
}
function workDirectory(type){
  const rel='../';
  if(type==='projects'){
    return shell({ rel, path:'projects/', title:'Projects', desc:'Shipped, peer-approved project case studies — the proof is public.',
      crumbs:[['Home',rel+'index.html'],['Projects',null]],
      body:'<section class="section"><div class="container"><div class="section-head"><div><div class="lbl lbl-teal" style="margin-bottom:8px;">The Work · '+APPROVED_PROJECTS.length+' shipped</div><h1 class="t-h2">Built here, shipped for real</h1></div></div><p class="t-lede" style="margin-bottom:28px;">Every project here shipped from a Build Cycle and was approved by the team that made it. Open source, credited forever.</p><div class="cards dense all">'+APPROVED_PROJECTS.map(x=>projectTeaser(rel,x)).join('')+'</div></div></section>' });
  }
  if(type==='pods'){
    const current=PODS.filter(x=>x.status!=='shipped'), past=PODS.filter(x=>x.status==='shipped');
    return shell({ rel, path:'pods/', title:'Pods', desc:'The small teams Build Cycles run on — who they are and what they shipped.',
      crumbs:[['Home',rel+'index.html'],['Pods',null]],
      body:'<section class="section"><div class="container"><div class="section-head"><div><div class="lbl lbl-teal" style="margin-bottom:8px;">The Work · pods</div><h1 class="t-h2">Small teams, real problems</h1></div></div>'
      +'<p class="t-lede" style="margin-bottom:28px;">A pod is a handful of people who dig into one problem together. This cycle&rsquo;s pods are open — past pods show what shipping looks like.</p>'
      +'<div class="lbl lbl-teal" style="margin-bottom:12px;">This cycle</div><div class="cards dense all" style="margin-bottom:40px;">'+current.map(x=>podTeaser(rel,x)).join('')+'</div>'
      +'<div class="lbl lbl-teal" style="margin-bottom:12px;">Shipped</div><div class="cards dense all">'+past.map(x=>podTeaser(rel,x)).join('')+'</div>'
      +'</div></section>' });
  }
  return shell({ rel, path:'people/', title:'People', desc:'Public member portfolios — opt-in, artifact-first.',
    crumbs:[['Home',rel+'index.html'],['People',null]],
    body:'<section class="section"><div class="container"><div class="section-head"><div><div class="lbl lbl-teal" style="margin-bottom:8px;">The Work · people</div><h1 class="t-h2">The people behind the work</h1></div></div><p class="t-lede" style="margin-bottom:28px;">Public portfolios are opt-in — members choose what the world sees. The full community lives inside The Labs.</p><div class="cards dense all">'+PEOPLE.map(x=>personTeaser(rel,x)).join('')+'</div></div></section>' });
}

/* ── Emit ── */
function emitType(dir, pages){ // pages: Map<slug|'', html>  ('' = the directory index)
  const abs=path.join(ROOT,dir);
  fs.mkdirSync(abs,{recursive:true});
  // Orphan sweep: generated entity dirs + any stray generated flat .html files
  for(const entry of fs.readdirSync(abs,{withFileTypes:true})){
    const p=path.join(abs,entry.name);
    if(entry.isDirectory()){
      const idx=path.join(p,'index.html');
      if(fs.existsSync(idx)&&fs.readFileSync(idx,'utf8').includes(MARK)&&!pages.has(entry.name)){ fs.rmSync(p,{recursive:true}); console.log('  – removed orphan '+dir+'/'+entry.name+'/'); }
    } else if(entry.name.endsWith('.html')&&entry.name!=='index.html'){
      if(fs.readFileSync(p,'utf8').includes(MARK)){ fs.unlinkSync(p); console.log('  – removed orphan '+dir+'/'+entry.name); }
    }
  }
  for(const [slug,html] of pages){
    if(slug===''){ fs.writeFileSync(path.join(abs,'index.html'),html); continue; }
    fs.mkdirSync(path.join(abs,slug),{recursive:true});
    fs.writeFileSync(path.join(abs,slug,'index.html'),html);
  }
  console.log('✓ '+dir+': '+pages.size+' pages');
}
function assertUniqueSlugs(items,label){
  const seen=new Set();
  for(const it of items){ if(!it.slug) throw new Error(label+' item missing slug: '+(it.name||it.title||it.id));
    if(seen.has(it.slug)) throw new Error('duplicate '+label+' slug: '+it.slug); seen.add(it.slug); }
}
assertUniqueSlugs(EVENTS,'event'); assertUniqueSlugs(RESOURCES,'resource'); assertUniqueSlugs(Object.values(METROS),'metro');
assertUniqueSlugs(PROJECTS_PUBLIC,'project'); assertUniqueSlugs(PODS,'pod'); assertUniqueSlugs(PEOPLE.map(m=>({...m,slug:m.handle})),'person');

emitType('events',  new Map([...EVENTS.map(e=>[e.slug,eventPage(e)]), ['',directoryPage('events')]]));
emitType('library', new Map([...RESOURCES.filter(r=>r.status==='published').map(r=>[r.slug,resourcePage(r)]), ['',directoryPage('library')]]));
emitType('labs',    new Map([...Object.values(METROS).map(m=>[m.slug,labPage(m)]), ['',directoryPage('labs')]]));
emitType('about',   new Map([['', aboutPage()]]));
emitType('cycles',  new Map([['', cyclesPage()]]));
emitType('projects',new Map([...APPROVED_PROJECTS.map(pr=>[pr.slug,projectPage(pr)]), ['',workDirectory('projects')]]));
emitType('pods',    new Map([...PODS.map(pd=>[pd.slug,podPage(pd)]), ['',workDirectory('pods')]]));
emitType('people',  new Map([...PEOPLE.map(m=>[m.handle,personPage(m)]), ['',workDirectory('people')]]));

/* sitemap.xml */
const urls=['', 'about/','cycles/','events/','library/','labs/','projects/','pods/','people/']
  .concat(EVENTS.map(e=>'events/'+e.slug+'/'))
  .concat(RESOURCES.filter(r=>r.status==='published').map(r=>'library/'+r.slug+'/'))
  .concat(Object.values(METROS).map(m=>'labs/'+m.slug+'/'))
  .concat(APPROVED_PROJECTS.map(pr=>'projects/'+pr.slug+'/'))
  .concat(PODS.map(pd=>'pods/'+pd.slug+'/'))
  .concat(PEOPLE.map(m=>'people/'+m.handle+'/'))
  .concat(['stories.html']);
fs.writeFileSync(path.join(ROOT,'sitemap.xml'),
  '<?xml version="1.0" encoding="UTF-8"?>\n<!-- GENERATED by tools/generate.js -->\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
  +urls.map(u=>'  <url><loc>'+SITE_BASE+'/'+u+'</loc></url>').join('\n')
  +'\n</urlset>\n');
console.log('✓ sitemap.xml: '+urls.length+' URLs');
