/* ── Events — the content source for /events/ (this directory's generated pages)
   and index.html's event cards. THIS FILE IS THE CMS: edit here, then run
   `node tools/generate.js` and commit both.
   Mock data shaped like Luma's list-events response (production swap is
   fetch('/api/events') — OLOS proxies Luma server-side; docs/OLOS_BACKEND_CHANGES.md).
   `slug` is the URL contract: events/{slug}/ here ↔ /events/[slug] in production. */
const EVENTS=[
  // The six anchor events — free, public, first come first served. They are the
  // cycle's public rhythm and the bridge between the public community and upskillers.
  {api_id:'anchor-01', slug:'kickoff-summit', name:'Kickoff Summit — Civic & Elections Cycle', kind:'Summit', start_at:'2026-07-14T18:00', end_at:'2026-07-14T21:00', location_type:'in_person', location_name:'DC Public Library — Main branch', grad:'m-navy', cost:'Free', host:'The Upskilling Labs', desc:'Launch the cycle: meet the community, explore the theme, leave with one assignment — observe', body:['One night, one room, everyone who’s in. We open the Civic & Elections Cycle together: what the theme is, why it matters here, and how the next three months run.','You leave with one assignment — observe. Not solutions, not opinions. Things you’ve actually seen about how civic life works, or doesn’t. Those observations are the raw material the whole cycle builds on.'], gallery:['m-navy','m-teal','m-forest'], anchor:true},
  {api_id:'anchor-06', slug:'problem-sprint', name:'Problem Sprint', kind:'Cycle event', start_at:'2026-07-28T18:00', end_at:'2026-07-28T20:30', location_type:'in_person', location_name:'Main branch', grad:'m-forest', cost:'Free', host:'The Upskilling Labs', desc:'Investigate together: pods work the field observations into problem situations — the material the whole cycle builds on', body:['This is where raw observations become real problems. Pods sit down with everything the community noticed and work it into problem situations — specific, grounded, worth three months of effort.','Come see how sensemaking works in the open. If you filled out the field survey, this is where your observations go to work.'], gallery:['m-forest','m-teal','m-navy'], anchor:true},
  {api_id:'anchor-02', slug:'meet-the-pods', name:'Meet the Pods', kind:'Cycle event', start_at:'2026-08-18T18:00', end_at:'2026-08-18T20:30', location_type:'in_person', location_name:'Main branch', grad:'m-teal', cost:'Free', host:'The Upskilling Labs', desc:'Discovery goes public: pods present Problem Situations, stakeholder maps, and paradoxes. Bring your expertise and introductions', body:['Discovery goes public. Every pod presents what they found: the problem situation, the people inside it, and the paradox that makes it hard.','You don’t need to be in the cycle to matter here. Bring your expertise, your questions, and your introductions — a single "you should talk to..." can change a pod’s whole direction.'], gallery:['m-teal','m-navy','m-forest'], anchor:true},
  {api_id:'anchor-03', slug:'hackathon-frame-sprint', name:'Hackathon — the Frame Sprint', kind:'Cycle event', start_at:'2026-09-08T09:00', end_at:'2026-09-08T18:00', location_type:'in_person', location_name:'Main branch', grad:'m-forest', cost:'Free', host:'The Upskilling Labs', desc:'Not primarily about coding: pods synthesize research into new frames, and projects emerge', body:['Not primarily about coding. A full day where pods take everything they’ve learned and reframe it — new ways of seeing the problem that make new solutions possible.','Projects are born here. By the end of the day, proposals exist, teams start forming, and the building phase has a shape.'], gallery:['m-forest','m-navy','m-teal'], anchor:true},
  {api_id:'anchor-04', slug:'meet-the-projects', name:'Meet the Projects', kind:'Cycle event', start_at:'2026-09-15T18:00', end_at:'2026-09-15T20:30', location_type:'in_person', location_name:'Main branch', grad:'m-teal', cost:'Free', host:'The Upskilling Labs', desc:'Projects go public: the community critiques the framing before the prototype', body:['Projects go public before a single prototype exists — on purpose. The community critiques the framing while changing course is still cheap.','Come poke holes. The teams want it. A hard question tonight saves a month of building the wrong thing.'], gallery:['m-teal','m-forest','m-navy'], anchor:true},
  {api_id:'anchor-05', slug:'showcase-summit', name:'Showcase Summit', kind:'Summit', start_at:'2026-10-13T18:00', end_at:'2026-10-13T21:00', location_type:'in_person', location_name:'DC Public Library — Main branch', grad:'m-navy', cost:'Free', host:'The Upskilling Labs', desc:'Prototypes, findings, failures, lessons — everything returns to the commons. Registration for the next cycle opens here', body:['The cycle ends the way it started: everyone in one room. Prototypes, findings, failures, lessons — all of it presented, all of it returned to the commons under open licenses.','Registration for the next cycle opens tonight. If you’ve been watching from the edge, this is the night to stop watching.'], gallery:['m-navy','m-forest','m-teal'], anchor:true},
  {api_id:'evt-001', slug:'prompting-for-real-work', name:'Prompting for real work', start_at:'2026-07-09T18:00', end_at:'2026-07-09T20:00', location_type:'in_person', location_name:'DC Public Library', img:'assets/sample-workshop-recap.png', cost:'Free', host:'Priya Shah · Product & AI mentor', desc:'A hands-on intro to prompting for everyday work', bring:'A laptop and a real task to try', body:['Two hours, one real task. You bring something from your actual week — an email backlog, a messy dataset, a report nobody reads — and leave with a working way to do it faster.','No theory without practice. No practice without your own work on the table. That’s the whole format.'], gallery:['m-teal','m-forest','m-navy']},
  {api_id:'evt-002', slug:'design-for-non-designers', name:'Design for non-designers', start_at:'2026-07-16T18:00', end_at:'2026-07-16T20:00', location_type:'in_person', location_name:'Tenley-Friendship', grad:'m-forest', cost:'Free', host:'The Upskilling Labs', desc:'Practical design fundamentals for builders', bring:"Something you'd like to make look better", body:['You don’t need to be a designer. You need about six rules and the discipline to use them. This session gives you both.','Bring something you’ve made that looks almost right. We’ll fix it together, and you’ll see exactly which rule was missing.'], gallery:['m-forest','m-teal','m-navy']},
  {api_id:'evt-003', slug:'energy-climate-roundtable', name:'Energy & Climate Roundtable', start_at:'2026-07-22T19:00', end_at:'2026-07-22T20:30', location_type:'virtual', location_name:'Online', img:'assets/sample-square-event.png', cost:'Free', host:'The Upskilling Labs', desc:'A community discussion on energy & climate work', body:['An open conversation about energy and climate work in our region — who’s doing it, what’s stuck, and where builders could actually help.','Roundtable means roundtable. Come ready to talk, not just listen. The link arrives after you save a spot.'], gallery:['m-navy','m-teal','m-forest']},
  {api_id:'evt-004', slug:'ship-your-first-ai-tool', name:'Ship your first AI tool', start_at:'2026-07-29T18:00', end_at:'2026-07-29T21:00', location_type:'in_person', location_name:'Main branch', grad:'m-teal', cost:'Free', host:'Priya Shah · Product & AI mentor', desc:'Build and ship a small AI tool, start to finish', bring:'A laptop — no coding experience needed', body:['Three hours from blank page to shipped. Small on purpose: one input, one output, one thing it does well.','No coding experience needed — the tools have changed, and this session is the proof. You leave with a link you can send to someone.'], gallery:['m-teal','m-navy','m-forest']},
  {api_id:'evt-005', slug:'build-night-ship-something-small', name:'Build night: ship something small', start_at:'2026-08-06T18:00', end_at:'2026-08-06T21:00', location_type:'in_person', location_name:'Main branch', grad:'m-forest', cost:'Free', host:'The Upskilling Labs', desc:'An open work session to ship something small', bring:"Whatever you're working on", body:['No agenda, no speaker. A room full of people getting real work done, with help nearby when you’re stuck.','The only rule: pick something small enough to finish tonight. Shipping is a habit, and habits are built in reps.'], gallery:['m-forest','m-navy','m-teal']},
  {api_id:'evt-006', slug:'data-storytelling', name:'Data storytelling', start_at:'2026-08-13T19:00', end_at:'2026-08-13T20:30', location_type:'virtual', location_name:'Online', grad:'m-navy', cost:'Free', host:'Marcus Bell · Data mentor', desc:'Turn data into a story people remember', body:['A chart nobody remembers is a chart that didn’t work. This session is about the difference between showing data and telling its story.','We’ll rebuild three real charts live — same numbers, completely different impact. You’ll never label an axis the same way again.'], gallery:['m-navy','m-forest','m-teal']},
  {api_id:'evt-007', slug:'mentor-office-hours', name:'Mentor office hours', start_at:'2026-08-20T17:00', end_at:'2026-08-20T19:00', location_type:'in_person', location_name:'DC Public Library', grad:'m-teal', cost:'Free', host:'The Labs mentor bench', desc:'Drop in for 1:1 time with a mentor', body:['Twenty minutes, one mentor, your actual problem. Product, data, design, engineering, strategy — the bench covers it.','Come with the thing you’re avoiding. That’s always the right thing to bring.'], gallery:['m-teal','m-forest','m-navy']},
  {api_id:'evt-008', slug:'community-showcase-night', name:'Community showcase night', start_at:'2026-08-27T18:00', end_at:'2026-08-27T20:30', location_type:'in_person', location_name:'Main branch', grad:'m-forest', cost:'Free', host:'The Upskilling Labs', desc:'See what the community shipped this cycle', body:['Five-minute demos, real work, honest lessons. See what the community shipped — and what shipping actually took.','The fastest way to believe you could do this is watching someone like you do it. Come watch. Then come build.'], gallery:['m-forest','m-teal','m-navy']}
];
if (typeof module !== 'undefined' && module.exports) module.exports = { EVENTS };
